### PR TITLE
Added --save to enable saving to config.xml

### PR DESCRIPTION
**Pull request by casz**

### CODE REVIEW

**Comment by casz** [comment]
@dpa99c Hi there :) Anything I can change/fix?

**Comment by dpa99c** [comment]
Hi, thanks for this. Sorry, it's taken a while - been very busy at work, so open-source stuff has had to wait. I'll bump the package version and push this out to npm.

**Comment by dpa99c** [comment]
published as cordova-check-plugins@1.1.1

**Comment by casz** [comment]
Cannot believe this was my first PR 💪
Thanks @dpa99c for accepting my PR with no description 😆
To think I have reached the milestone of 2000 contributions in the last year.
Again many thanks for sparking my interest in open source!

https://firstpr.me/#casz

**Pull request merged**
